#cloud-config

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL6DIQ+E+sAaDni3VJlnxDJp6LF0s1r6SmbU6P1YMHtQ stevenxie

rancher:
  network:
    interfaces:
      eth*:
        dhcp: true
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
  services:
    - iptables-rules:
        image: yourname/iptables-rules
        command: ./set-rules.sh  # can be omitted if set in Dockerfile with ENTRYPOINT or CMD
        net: host
        privileged: true
        labels:
          io.rancher.os.scope: system
          io.rancher.os.detach: false
          io.rancher.os.remove: true
        links:
        - network
