# container-linux-config

ignition:
  # Prevent infinite HTTP(s) resource loading
  timeouts:
    http_response_headers: 10
    http_total: 30


passwd:
  users:
    - name: dev
      primary_group: users
      groups: [ sudo, docker, systemd-journal ]
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL6DIQ+E+sAaDni3VJlnxDJp6LF0s1r6SmbU6P1YMHtQ stevenxie


storage:
  files:
    # Configure .bashrc and .bash_aliases
    - path: /home/dev/.bashrc
      filesystem: root
      user:
        name: dev
      group:
        name: users
      mode: 0644
      contents:
        inline: |
          # Test for an interactive shell.
          if [[ $- != *i* ]] ; then
                  # Shell is non-interactive.  Be done now!
                  return
          fi

          # Prioritize /opt/bin, add Node to PATH
          export NODEJS_HOME=/opt/lib/nodejs/node-v10.2.1/bin
          export PATH="$NODEJS_HOME:/opt/bin:$PATH"

          # Import custom aliases
          if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi

          # Enable custom colors and styling
          export CLICOLOR=1

          # Customize PS1
          PS1='\[\e[1;32m\]\u@\h\[\e[23m\]: \[\e[34m\]\w \[\e[34m\]\$\[\e[0m\] '
    - path: /home/dev/.bash_aliases
      filesystem: root
      user:
        name: dev
      group:
        name: users
      mode: 0644
      contents:
        inline: |
          #!/bin/bash

          ## Git:
          # git-stat -> git status
          alias git-stat="git status"

          # git-co -> git checkout
          alias git-co="git checkout"

          # git-br -> get name of current Git branch
          alias git-br="git branch | grep -e "^*" | cut -d' ' -f 2"

          # git-discard -> discard local changes in favor of remote data
          alias git-discard="git fetch --all && git reset --hard @{u}"

          ## Docker:
          # docker-prunei -> prunes docker images
          alias docker-prunei="docker image prune"

          # docker-prune -> docker container prune
          alias docker-prune="docker container prune"

          ## List:
          # ll -> show owner and permissions for a file/dir
          if [[ $(type -t ll) == "" ]]; then alias ll="ls -l"; fi

          # la -> list all files (including hidden)
          if [[ $(type -t la) == "" ]]; then alias la="ls -a"; fi

      # Configure custom .vimrc
    - path: /home/dev/.vimrc
      filesystem: root
      user:
        name: dev
      group:
        name: users
      mode: 0644
      contents:
        inline: |
          "" CUSTOM VIM CONFIG
          " filetype plugin indent on
          " syntax on

          "" General
          set number        " Show line numbers
          set wrap
          set wrapmargin=0
          set linebreak     " Break lines at word (requires Wrap lines)
          set nolist
          set showbreak=+++ " Wrap-broken line prefix
          set textwidth=0   " Line wrap (number of cols)
          set showmatch     " Highlight matching brace
          set errorbells    " Beep or flash screen on errors

          set hlsearch      " Highlight all search results
          set smartcase     " Enable smart-case search
          set ignorecase    " Always case-insensitive
          set incsearch     " Searches for strings incrementally

          set autoindent    " Auto-indent new lines
          set shiftwidth=4  " Number of auto-indent spaces
          set smartindent   " Enable smart-indent
          set smarttab		" Enable smart-tabs
          set softtabstop=4	" Number of spaces per Tab

          "" Advanced
          set ruler	        " Show row and column ruler information
          set undolevels=1000               " Number of undo levels
          set backspace=indent,eol,start    " Backspace behaviour

      # Configure `sshd`, prevent password authentication
    - path: /etc/ssh/sshd_config
      filesystem: root
      mode: 0600
      contents:
        inline: |
          UsePrivilegeSeparation sandbox
          Subsystem sftp internal-sftp
          ClientAliveInterval 180
          UseDNS no
          UsePAM no

          PermitRootLogin no
          AllowUsers core dev
          AuthenticationMethods publickey
          PrintMotd no

      # Restrict networking to :443, :80, :22, and internal ports
    - path: /var/lib/iptables/rules-save
      filesystem: root
      mode: 0644
      contents:
        inline: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          -A INPUT -i lo -j ACCEPT
          -A INPUT -i eth1 -j ACCEPT
          -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
          COMMIT


systemd:
  units:
      # Enable autoloading of iptables
    - name: iptables-restore.service
      enabled: true

      # Install docker-compose
    - name: docker-compose-installer.service
      enabled: true
      contents: |
        [Unit]
        Description=Docker Compose installer
        After=systemd-networkd.service
        Requires=systemd-networkd.service
        ConditionPathExists=!/opt/bin/docker-compose

        [Service]
        Type=oneshot
        ExecStartPre=/bin/mkdir -p /opt /opt/bin
        ExecStart=/bin/curl -o /opt/bin/docker-compose \
                            -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        ExecStartPost=/bin/chmod +x /opt/bin/docker-compose

        [Install]
        WantedBy=multi-user.target

      # Install Node
    - name: node-installer.service
      enabled: true
      contents: |
        [Unit]
        Description=Node.js installer
        After=systemd-networkd.service
        Requires=systemd-networkd.service
        ConditionPathExists=!/usr/local/lib/nodejs

        [Service]
        Type=oneshot
        ExecStartPre=/bin/curl -o /tmp/node-pkg.tar.xz https://nodejs.org/dist/v10.2.1/node-v10.2.1-linux-x64.tar.xz
        ExecStartPre=/bin/mkdir -p /opt /opt/lib /opt/lib/nodejs
        ExecStart=/bin/tar -xJvf /tmp/node-pkg.tar.xz -C /opt/lib/nodejs
        ExecStartPost=/bin/mv /opt/lib/nodejs/node-v10.2.1-linux-x64 /opt/lib/nodejs/node-v10.2.1
        ExecStartPost=/bin/rm /tmp/node-pkg.tar.xz

        [Install]
        WantedBy=yarn-installer.service

      # Install Yarn
    - name: yarn-installer.service
      enabled: true
      contents: |
        [Unit]
        Description=Yarn installer
        After=node-installer.service
        Requires=node-installer.service
        ConditionPathExists=!/home/dev/.yarn/bin/yarn

        [Service]
        Type=oneshot
        User=dev
        ExecStartPre=/bin/curl -o /tmp/yarn-install.sh -L https://yarnpkg.com/install.sh
        ExecStartPre=+/bin/chmod +x /tmp/yarn-install.sh
        ExecStart=-/bin/sh /tmp/yarn-install.sh
        ExecStartPost=/bin/rm /tmp/yarn-install.sh

        [Install]
        WantedBy=multi-user.target


update:
  group: "beta"
  server: "https://public.update.core-os.net/v1/update/"


# Until 'etcd' is configured, do not automatically reboot upon updates
locksmith:
  reboot_strategy: "off"
